### ISSUE TITLE
Add support for wireguard interface

### ISSUE THREAD

**Issue by FilipK-CZ** [ansible-collections/vyos.vyos#133]
##### SUMMARY
Add support for parsing wireguard interface like wg01 in vyos.vyos.vyos_interfaces parameter name

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vyos.vyos.vyos_interfaces

##### ADDITIONAL INFORMATION
Better and much easier managing wireguard interfaces, state option using vyos_interfaces.
The main problem with using vyos.vyos.vyos_config is missing the state option and it's needed to make advanced when conditions for setup peers. Also, vyos_config is every time in the changed state
 
```yaml
FROM
- name: Setup wireguard interface wg01
  vyos.vyos.vyos_config:
    lines:
    - set interfaces wireguard wg01 description WGTunnel
    - set interfaces wireguard wg01 port 51820
    - set interfaces wireguard wg01 address 172.31.0.1/24
    
- name: Adding wireguard users for wg01
  vyos.vyos.vyos_config:
    lines:
    - set interfaces wireguard wg01 peer TestTunnel allowed-ips 172.31.0.2/32
    - set interfaces wireguard wg01 peer TestTunnel pubkey xxxxxxxxx

TO (example)
- name: setup wg01
  vyos.vyos.vyos_interfaces:
    config:
    - name: wg01
      description: Configured by Ansible
      enabled: true
      port: 51820
      address: 172.31.0.1/24
      peer:
        - name: TestTunnel
          allowed_ips: 172.31.0.2/32
          pubkey: xxxxxxxxx
```
