### ISSUE TITLE
vyos_firewall_rules: Support for `log enable` on individual rules

### ISSUE THREAD

**Issue by chenxiaolong** [ansible-collections/vyos.vyos#235]
##### SUMMARY

It looks like the `vyos_firewall_rules` module currently supports enabling logging for the default rule, but not for user-specified rules. Specifically, it doesn't seem like it's currently possible to set: https://docs.vyos.io/en/latest/configuration/firewall/index.html#cfgcmd-set-firewall-name-name-rule-1-999999-log-disable-enable

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`vyos_firewall_rules`

##### ADDITIONAL INFORMATION

I'd imagine a new field might look something like:

```yaml
- vyos.vyos.vyos_firewall_rules:
    config:
      - afi: ipv6
        rule_sets:
         - name: wan-lan
            rules:
              - number: 2
                action: drop
                state:
                  invalid: true
                log: true
```
