### ISSUE TITLE
Firewall rule ICMPv6 type wrongly transformed

### ISSUE THREAD

**Issue by HON95** [ansible-collections/vyos.vyos#257]
##### SUMMARY
Specifying `icmp.icmp_type: echo-request` in an IPv6 firewall rule should translate to `icmpv6 { type-name echo-request }` in VyOS, but is translated to `icmpv6 { type echo-request }` and gives a VyOS config error instead.

I think this was changed in VyOS sometime during 1.4-rolling since i can see the `icmpv6 { type echo-request }` variant in my old configs (1.4-rolling-202105050912), but 1.4-rolling-202205100602 refuses to accept it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vyos.vyos.vyos_firewall_rules

##### ANSIBLE VERSION
```
ansible [core 2.12.5]
  config file = /home/hon/Projects/HON95/private-configs/ansible.cfg
  configured module search path = ['/home/hon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/hon/.ansible/collections:/usr/share/ansible/collections
  executable location = /sbin/ansible
  python version = 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
# /usr/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
vyos.vyos  2.8.0

# /home/hon/.ansible/collections/ansible_collections
Collection Version
---------- -------
vyos.vyos  3.0.0
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(/home/hon/Projects/HON95/private-configs/ansible.cfg) = ['/home/hon/Projects/HON95/private-configs/ansible-hon/roles', '/home/hon/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
HOST_KEY_CHECKING(/home/hon/Projects/HON95/private-configs/ansible.cfg) = False
INTERPRETER_PYTHON(/home/hon/Projects/HON95/private-configs/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/home/hon/Projects/HON95/private-configs/ansible.cfg) = 60
```

##### OS / ENVIRONMENT
OS (host): Arch Linux
Ansible version: 2.12.5
Python version (host): 3.10.4
vyos collection version: 3.0.0
VyOS version: 1.4-rolling-202205100602

##### STEPS TO REPRODUCE
Run the play below against a VyOS 1.4 router.

```yaml
- name: 'Set firewall rules'
  vyos.vyos.vyos_firewall_rules:
    state: overridden
    config:
      - afi: ipv6
        rule_sets:
          - name: apps-main-out-6
            default_action: reject
            rules:
              - number: 100
                description: "yolo"
                protocol: icmpv6
                # Here
                icmp:
                  type_name: echo-request
                action: accept
```

##### EXPECTED RESULTS
Modules tries to set `set firewall ipv6-name apps-main-out-6 rule 100 icmpv6 type-name echo-request`.

Running this config command directly in VyOS 1.4 succeeds.

##### ACTUAL RESULTS
Modules tries to set `set firewall ipv6-name apps-main-out-6 rule 100 icmpv6 type echo-request`.

Error from running the playbook:
```
fatal: [router]: FAILED! => {"changed": false, "module_stderr": "set firewall ipv6-name apps-main-out-6 rule 100 icmpv6 type echo-request\r\n\r\r\n  'echo-request' is not a valid integer number\r\n  \r\n  \r\n  \r\n  Invalid value\r\n  Value validation failed\r\n  Set failed\r\n\r\n\r[edit]\r\r\nansible@router# ", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
```

Alternatively, using `icmp.type_name: 128` gives `value of type_name must be one of: any, echo-reply [...], got: 128`, but does actually set `icmpv6 { type 128 }` in the config. Running the task again but with `icmp.type*` removed gives the same error as it seemingly fails to parse the remote config until it is manually removed in the VyOS CLI.

Alternatively, using `icmp.type: 128` gives `value of type_name must be one of: any, echo-reply [...], got: 128`.

Running this config command directly in VyOS 1.4 gives the same error.
