### ISSUE TITLE
[vyos_banner] ansible_connection failure

### ISSUE THREAD

**Issue by brahmanim** [ansible-collections/vyos.vyos#324]
##### SUMMARY

The Integration tests failed on a task [Run CLI tests](https://github.com/ansible-collections/vyos.vyos/blob/f1213dece775d30f6653182bfecee1a47d1e6504/tests/integration/targets/vyos_banner/tasks/cli.yaml#L14).
I think that the is no need to specify `ansible_connection=ansible.netcommon.network_cli`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vyos_banner

##### ANSIBLE VERSION

```paste below
2.14
```

##### COLLECTION VERSION

```paste below
vyos 4.0.2
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

Version: VyOS 1.1.8

##### STEPS TO REPRODUCE

Run integration tests task [Run CLI tests](https://github.com/ansible-collections/vyos.vyos/blob/f1213dece775d30f6653182bfecee1a47d1e6504/tests/integration/targets/vyos_banner/tasks/cli.yaml#L14).

```yaml
- name: Run test case (connection=ansible.netcommon.network_cli)
  ansible.builtin.include_tasks: "{{ test_case_to_run }} ansible_connection=ansible.netcommon.network_cli"
  with_items: "{{ test_items }}"
  loop_control:
    loop_var: test_case_to_run
  tags:
    - network_cli
```

##### EXPECTED RESULTS

No connection error

##### ACTUAL RESULTS

```paste below
TASK [/usr/share/ansible/collections/ansible_collections/vyos/vyos/tests/integration/targets/vyos_banner : Run CLI tests] ***
task path: /usr/share/ansible/collections/ansible_collections/vyos/vyos/tests/integration/targets/vyos_banner/tasks/main.yaml:2
ERROR! Invalid options for ansible.builtin.include_tasks: ansible_connection

The error appears to be in '/usr/share/ansible/collections/ansible_collections/vyos/vyos/tests/integration/targets/vyos_banner/tasks/cli.yaml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Run test case (connection=ansible.netcommon.network_cli)
  ^ here
```
