### ISSUE TITLE
Include openvpn interfaces in ansible_network_resources in output form vyos_facts

### ISSUE THREAD

**Issue by np422** [ansible-collections/vyos.vyos#83]
##### SUMMARY

The name and ip-address of openvpn interfaces are missing in the information gathered by the vyos_facts module

##### ISSUE TYPE

Ipsec vti-interfaces are already included in the ansible_network_resources.l3_interfaces, but openvpn vtun interfaces are missing.

##### COMPONENT NAME

vyos_facts

##### ADDITIONAL INFORMATION

My use-case is that I'm trying to automate creation and verification of firewall rules. We use openvpn for site2site tunnels and have firewall rules for those interfaces as well. Currently we are using a workaround by manually listing openvpn interfaces as host_vars, but it would be great to be able to dynamically discover openvpn interfaces in the same way as ethernet interfaces and ipsec interfaces.

```yaml

    - name: Extract the interface list 
      set_fact:
        vyos_facts_interfaces: "{{ ansible_facts | json_query(_query) | list }}"
      vars:
        _query: "ansible_network_resources.l3_interfaces[].name"

    - name: Crete all firewall rules for the interfaces based on yaml-configuration
      include_tasks: template_interface_rules.yml
      with_items: "{{ vyos_facts_interfaces }}"
      loop_control:
        loop_var: interface
```

Currently the vyos_facts_interfaces variable will contain all ethternet and ipsec interfaces, but the vtunX interfaces from openvpn connections are missing.
