### ISSUE TITLE
vyos_static_routes cannot be used to create interface-routes due to requirement for a forward router address

### ISSUE THREAD

**Issue by mhuxtable** [ansible-collections/vyos.vyos#92]
##### SUMMARY

The `vyos_static_routes` module requires that a `forward_router_address` be specified on each route. This precludes use of this module to create static `interface-route` entries in the VyOS configuration.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`vyos.vyos.vyos_static_routes`

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /Users/matt/code/ziglu/i12e/gps/vpn/ansible/ansible.cfg
  configured module search path = ['/Users/matt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 27 2020, 20:54:22) [Clang 11.0.3 (clang-1103.0.32.59)]

```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

VyOS hosts, but problem is with the module's API surface in the latest release, so not really applicable

##### STEPS TO REPRODUCE

```yaml
- vyos.vyos.vyos_static_routes:
     config:
       - address_families:
           - afi: ipv4
             routes:
               - destination: "192.168.0.0/24"
                 next_hops:
                   - interface: eth1
```

##### EXPECTED RESULTS

An interface-route is created in the VyOS config as follows:

```
protocols {
    static {
        interface-route 192.168.0.0/24 {
            next-hop-interface eth1 {
            }
        }
    }
}
```

##### ACTUAL RESULTS

The run fails because `forward_router_address` is a required argument for the module.

```paste below
fatal: [hostname]: FAILED! => changed=false
  msg: 'missing required arguments: forward_router_address found in config -> address_families -> routes -> next_hops'

```
